-- ============================================================
-- JASLIN MIGRATION 001
-- BASE SCHEMA
-- ============================================================

begin;

-- ------------------------------------------------------------
-- USERS
-- ------------------------------------------------------------
create table if not exists public.users (
    telegram_id text primary key,
    username text,
    first_name text,
    wallet text default '',
    balance numeric(30,8) not null default 0,
    mining_started_at bigint not null,
    last_spin_at bigint not null default 0,
    referred_by text,
    created_at bigint not null
);

create index if not exists idx_users_referred_by
    on public.users(referred_by);

-- ------------------------------------------------------------
-- TRANSACTIONS
-- ------------------------------------------------------------
create table if not exists public.transactions (
    id bigint generated by default as identity primary key,
    telegram_id text not null,
    type text not null,
    amount numeric(30,8) not null,
    status text not null default 'completed',
    tx_signature text,
    note text,
    created_at bigint not null
);

create index if not exists idx_transactions_telegram_id
    on public.transactions(telegram_id);

create index if not exists idx_transactions_created_at
    on public.transactions(created_at desc);

-- ------------------------------------------------------------
-- BASIC RLS
-- ------------------------------------------------------------
alter table public.users
    enable row level security;

alter table public.transactions
    enable row level security;

-- Access is handled through the trusted backend/service role.
revoke all on table public.users
    from anon, authenticated;

revoke all on table public.transactions
    from anon, authenticated;

grant all on table public.users
    to service_role;

grant all on table public.transactions
    to service_role;

commit;

-- ============================================================
-- END MIGRATION 001
-- ============================================================--
--   002_x_tasks.sql
--   003_auto_withdraw.sql
--   004_security_hardening.sql
--
-- ============================================================
-- END OF MIGRATION 001 PLACEHOLDER
-- ============================================================
